### ISSUE TITLE
Create wiki/repo structure

### ISSUE THREAD

**Issue by nebw** [BioroboticsLab/organization#1]

**Comment by Sh4kE** [comment]
Do you really wan't a new repository only for the wiki? I'd rather suggest putting it into the biotracker_core repository? What do you think?

**Comment by timlandgraf** [comment]
The Github page of the Biorobotics Lab has too many projects and repos. The wiki would list all projects within the Biorobotics Lab in a nice, structured way. Think of it as the index page if you will.
