### ISSUE TITLE
Organise thesis

### ISSUE THREAD

**Issue by ls1xt** [BioroboticsLab/organization#14]
Add a bibtex file with all the thesis written in the lab. The bibtex annotation should include the URL to the thesis pdf. With a simple bash script it should be possible to download all the PDFs.

**Comment by timlandgraf** [comment]
PDFs that are published online are crawled by Google Scholar and therefor could be added to a list, bibtex export possible. It would be great to somehow automate adding new documents to the list...

**Comment by ls1xt** [comment]
Hmm, there are probably less then 10 theses per year. I guess it is more work to automate it, then simply adding a bibtex entry per thesis manually.

**Comment by timlandgraf** [comment]
I'll be at least 6 years in science, so at least 60 theses. likely more. maybe there is already something we can configure accordingly...

**Comment by ktugan** [comment]
we have zotero for it now
