### ISSUE TITLE
Frame IDs are currently not unique (CAPNP)

### ISSUE THREAD

**Issue by walachey** [BioroboticsLab/organization#15]
bb_binary::Frame.id [1] is not unique. Reported by @ktugan.

This makes further evaluation hard; especially mapping detections back to frame containers.

Copying and modifying the frame containers with the capnp schema might take longer than recalculating the whole data [2] (@ktugan). (If not executed on the Cray, that is).

[1] https://github.com/BioroboticsLab/bb_binary/blob/master/bb_binary/bb_binary_schema.capnp#L64
[2] https://gist.github.com/ktugan/a80a0d1641216f38fe7c1b59cde44352

**Comment by ktugan** [comment]
Current workaround which is kinda hacky:
Replace following line in `bb_tracking/data/datawrapper_binary.py`:
`detection_id = 'f{}d{}c{}'.format(frame.id, detection.idx, cam_id)`
with 
`detection_id = 'f{}d{}c{}'.format(frame.timestamp, detection.idx, cam_id)`

This is untested but reduces the chance of error occurence. It works most of the time but is only, like previously mentioned, a workaround.

**Comment by hmoenck** [comment]
Uhh, even for a workaround it seems to be a better idea to combine id and timestamp into one identifier. Because, as stated correctly, the timestamp is no way unique, so this will fairly reduce chances of collision.

**Comment by ktugan** [comment]
The problem is currently that frame id is unfortunately not unique, or which id do you mean?
But another non collision would be possible to include cam_id in the identifier to make it unique, that means timestamp + cam_id

**Comment by ktugan** [comment]
We discussed in the meeting that for new data (2016) frame_ids are indeed unique. This is unfortunately not so:

![image](https://cloud.githubusercontent.com/assets/266548/21869423/dc8ac2a4-d857-11e6-8a39-7a49b434286a.png)

The code should be checked again.

**Comment by ktugan** [comment]
Bei mir auf dem Rechner (und allen anderen getesteten) funktioniert folgender code:
```
import uuid
frame_id = uuid.uuid4().int >> 64
frame_id
```

**Comment by ktugan** [comment]
added new copy function which is faster by a factor of 200, gist stays the same:

https://gist.github.com/ktugan/a80a0d1641216f38fe7c1b59cde44352

**Comment by ktugan** [comment]
Whats the status of this ticket? Can it be closed?
