### ISSUE TITLE
implement solution to display video with marked bees based on tracks

### ISSUE THREAD

**Issue by walachey** [BioroboticsLab/organization#17]
Given a track, the video containing the track needs to be fetched, the tracked bee needs to be highlighted. 

Preliminary work exists (@ktugan).

This is a requirement of ground truth data generation for interns.

**Comment by ktugan** [comment]
update: solution is nearly deployable, some requirements on the servers are missing

Code under: [https://github.com/ktugan/beesbook_backend](https://github.com/ktugan/beesbook_backend)

**Comment by ktugan** [comment]
update: the indexing of the repo takes a very long time, probably because the data is on the nas only

**Comment by ktugan** [comment]
indexing finished for 2016, backend now usable
