### ISSUE TITLE
sudo rechte auf flip

### ISSUE THREAD

**Issue by ktugan** [BioroboticsLab/organization#23]
Wer von denen braucht noch admin rechte?
```
ktugan@flip:~$ cat /etc/group | grep sudo
sudo:x:27:leon,ben,michael,julian,jopio,ktugan
```

**Comment by ktugan** [comment]
Removed michael and jopio as sudo users. Re-add if necessary. What about julian? Does he require sudo?

**Comment by hmoenck** [comment]
Michael needed them for his thesis. He was working on jenkins and needed administrative rights for install purposes. It seems like he has been inactive for quite a while (>4 month). Check on issue #12 
Not sure about jopio, though. I'm sure you'll be notified if he still needs sudo. ;)
I guess julian is the account of @justayak . He finished his thesis a longer while ago and I think he doesn't really need sudo anymore.
On the other hand, I'd like to have sudo on flip. Account is "hauke".

**Comment by ktugan** [comment]
julian nun raus und hauke drin
