### ISSUE TITLE
(Selectively) import redmine wiki pages

### ISSUE THREAD

**Issue by nebw** [BioroboticsLab/organization#6]

**Comment by timlandgraf** [comment]
Ich denke diese sollten es sein:

https://maserati.mi.fu-berlin.de/redmine/projects/brl/wiki/HowToStartYourWorkInTheLab_
https://maserati.mi.fu-berlin.de/redmine/projects/brl/wiki/OrganisationOfTheBRL_
https://maserati.mi.fu-berlin.de/redmine/projects/brl/wiki/Documentation_
https://maserati.mi.fu-berlin.de/redmine/projects/brl/wiki/HowToWriteAThesis
https://maserati.mi.fu-berlin.de/redmine/projects/brl/wiki/FinishedTheses_

**Comment by timlandgraf** [comment]
Achtung: sind alle in Deutsch. Übersetzen würde ich aber nicht.
