### ISSUE TITLE
Create a new in the lab page

### ISSUE THREAD

**Issue by ls1xt** [BioroboticsLab/organization#8]
Provide use full information about:
- getting an Slack acocunt
- weekly meetings

**Comment by b2m** [comment]
There are also a lot of platforms that you should now about and how to access them (Github, Gitlab, Flip, Trello, Dropbox, Google Drive, Maillinglist, Slack, YouTube, WordPress, Zotero, Coverall, ReadTheDocs, Travis, Liste der Abschlussarbeiten im Fachbereich...).

Should we organize them in a public wiki?

**Comment by timlandgraf** [comment]
What kind of info you want to provide in the wiki?

**Comment by b2m** [comment]
Just the name of the platform, the url, what the platform is used for and how to get access to it (who to ask, or where to register). This is the unordered list I am using (some plattforms missing or not used anymore):

| Plattform | Url | Used for | How to get access |
| --- | --- | --- | --- |
| GitHub | https://github.com/BioroboticsLab/ | Organizing code | Ask @nebw  and do not forget to join a Team |
| Travis | https://travis-ci.org/BioroboticsLab/ | CI Server for GitHub projects | Synced with your GitHub account |
| Coveralls | https://coveralls.io/github/BioroboticsLab/ | Code Coverage for GitHub projects | Synced with your GitHub account |
| Website Lab | http://biorobotics.mi.fu-berlin.de/wordpress/ | ... | no account needed |
| Website BeesBook Projekt | http://beesbook.mi.fu-berlin.de/wordpress/ | ... | no account needed |
| Slack | https://fubioroboticslab.slack.com | Lab communication | ask @nebw |
| Gitlab | https://git.imp.fu-berlin.de/bioroboticslab/ | Private repositories for students | Zedat Account and ask @nebw |
| Mailingliste BeesBook | https://lists.fu-berlin.de/listinfo/beesbook | Announcements | Register via form on page |
| Mailingliste BioRobotik | https://lists.fu-berlin.de/listinfo/biorobotics | Announcements | Register via form on page |
| Abschlussarbeiten Fachbereich | http://www.mi.fu-berlin.de/inf/groups/ag-ki/Theses/index.html | Official list of theses | no account needed |
| Paper | https://www.zotero.org/groups/bioroboticslab/ | Organize interesting papers | Register and join group |

**Comment by timlandgraf** [comment]
yep make sense. let's do it!

**Comment by ktugan** [comment]
already done: [https://github.com/BioroboticsLab/organization/wiki/Plattformen](https://github.com/BioroboticsLab/organization/wiki/Plattformen)
